services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=PizzaBot

  app:
    build: .
    image: bot:1.0.0
    depends_on:
      - db